### ISSUE TITLE
Problems with abnormal leg movements

### ISSUE THREAD

**Issue by RuiqingTang** [rongakowang/MMDMC#1]
When this command is finished
`python export.py --extract_vmd`
I got a lot of vmd files, but they all had the same problem.
![image](https://github.com/user-attachments/assets/dacc2c30-f55d-4dc7-970e-1fe5f8eb10e5)
Its legs seemed to be drawn by an invisible force

**Comment by rongakowang** [comment]
Hi,

which character are you using and can you please check what the extracted BVH looks like?

**Comment by RuiqingTang** [comment]
I downloaded the character named '凝光' from the `character_list.csv` provided.
![image](https://github.com/user-attachments/assets/6ecea4cb-13a3-4b07-ad12-0c706df4e279)
I imported the BVH file into blender and played it, except for the slow animation, everything was fine.
Its movements appear to be normal.

**Comment by rongakowang** [comment]
Hi,

Thank you for your reply, I had a quick test on the character and the vmd looks fine to me. If you directly play back the vmd file, you need to turn off the foot IK in the mmd_tools, make sure the panel looks like this:

<img width="194" alt="Screenshot 2024-07-25 at 11 14 17 AM" src="https://github.com/user-attachments/assets/b2bc8ad5-ffac-4a8b-a520-844d4f37ac4f">

The slow motion can be caused by the rendering in blender, which you can check against the FPS. When you exported the blend file, all computations are baked and the animation should be in a normal speed.

**Comment by RuiqingTang** [comment]
Hi,
Thank you for your detailed answer @rongakowang , it works!

**Comment by RuiqingTang** [comment]
Hi,
I set all the IK transformations in the code to True, but I still get the same problem with the exported vmd files. Is there another solution? I can‘t turn off IK due to the existing vmd files support it.
```
bpy.data.objects[f'{char}_arm'].pose.bones["つま先ＩＫ.R"].mmd_ik_toggle = True
bpy.data.objects[f'{char}_arm'].pose.bones["つま先ＩＫ.L"].mmd_ik_toggle = True
bpy.data.objects[f'{char}_arm'].pose.bones["足ＩＫ.R"].mmd_ik_toggle = True
bpy.data.objects[f'{char}_arm'].pose.bones["足ＩＫ.L"].mmd_ik_toggle = True
```

**Comment by rongakowang** [comment]
Hi,

The IK code you are referring to is for exporting blend files, not vmd files. So you won't expect any changes in the vmd file.

Can you elaborate on what you mean "I can‘t turn off IK due to the existing vmd files support it." ?
