### ISSUE TITLE
How to bind textures automatically

### ISSUE THREAD

**Issue by czpcf** [rongakowang/MMDMC#2]
I follow the provided commands and successfully get the .blend file, but the materials/textures in the original .pmx file do not bind to the mesh.

<img width="197" alt="1" src="https://github.com/user-attachments/assets/ebf17249-cb4a-4edf-9b33-1637a79db686">

Is it possible to bind them automatically?

Thank you very much!

**Comment by rongakowang** [comment]
Hi, 

I am not familiar with how materials can be attached in bpy, for the visualization in our work, I baked the blender materials as mesh textures by exporting pmx files to obj. Since we are estimating the per-vertex displacements, the mesh topologies remain across frames and hence there will be no problems in uv textures.
